### PR TITLE
fix: remeber scroll position when go to previous page, resolve #16

### LINKED ISSUE #16: Remember scroll position when navigating back from the detail view to the main page
Would it be possible to add the code to remember the scroll position when navigating back to the home page after viewing a detail page?  Right now, when you scroll down on the home page, find a movie, click it to view details, then use the back button, it brings you back to the top of the home page instead of where you left off.

This is something I'm struggling with in my own nuxt3 project and would love to see how it can be done properly.

### PR DESCRIPTION
**Pull request by ali4zimi**
I used `localstorage` to store previous pages with their scroll position. When the user presses the back button they will be at the same location where they left off. I worked on this solution today and it works now. Please check it once more

### CODE REVIEW

**Comment by Atinux** [comment]
Thanks @ali4zimi 

Why using the localStorage since the navigation is on client-side actually, why not using a variable in memory instead?

**Comment by ali4zimi** [comment]
Thanks, @Atinux for reviewing it, I assumed when the user refreshes on the next page, the variable in the memory would be cleared.

**Comment by Atinux** [comment]
If he refreshed the browser will respect the position normally.

**Comment by antfu** [comment]
I actually wrote a library with @posva about this yesterday coincidentally https://github.com/antfu/vue-router-better-scroller

**Comment by antfu** [comment]
Thank you! Please check https://github.com/nuxt/movies/commit/83d466e54794ffa20ba14ae54526c0278e656fdb instead.

**Comment by ali4zimi** [comment]
Thanks, great library!
I needed this for one of my own projects.

**Pull request closed without merging**
