### PR TITLE
feat: add language switcher option

### PR DESCRIPTION
**Pull request by ali4zimi**
Now it is possible to switch the language despite detecting the browser's default language. I tried not to use refresh the page but I couldn't since some data are fetched at the beginning. If there is a better way please guide me.

### CODE REVIEW

**Comment by ali4zimi** [comment]
@antfu What if we add Pinia to this project and move some of the composable to pinia so that we can trigger the request after translation?

**Comment by antfu** [comment]
I don't see Pinia is required in this case, can you elaborate more?

**Comment by ali4zimi** [comment]
When the language is switched, all the messages are translated, but those texts which are fetched from the server remain unchanged.

**Comment by antfu** [comment]
I think currently doing a full-page refresh is good enough. Thanks!

**Pull request merged**
